### ISSUE TITLE
please clarify the copyright

### ISSUE THREAD

**Issue by doko42** [fedora-python/lxml_html_clean#6]
./LICENSE.txt:Copyright (c) 2004 Infrae. All rights reserved.

./docs/conf.py:copyright = '2024, Lumír Balhar'

That cannot be correct. the conf.py only describes the copyright of the project.

**Comment by frenzymadness** [comment]
Thank you. You are right, the file was probably generated when I added documentation here. I'm going to fix it.

**Comment by doko42** [comment]
how does this help? it' still a different author than the upstream author

**Comment by frenzymadness** [comment]
Right now, this project is basically a copy of a part of lxml so until we diverge significantly, we can keep also the settings. If there is anything wrong in the license or the doc settings, it should be reported to and fixed in lxml first.

**Comment by frenzymadness** [comment]
From the only documentation config present in the lxml project: https://github.com/lxml/lxml/blob/a9f31d9ba0f6db7b0c6576b4b9014a4ea7649eca/doc/api/conf.py#L10
