### ISSUE TITLE
Any plan to add inline type annotations?

### ISSUE THREAD

**Issue by abelcheung** [fedora-python/lxml_html_clean#8]
Hello, this is maintainer of [`types-lxml`](https://github.com/abelcheung/types-lxml), an external lxml annotation package. When `lxml` maintainer decided to drop `lxml.html.clean`, probably the same should apply to me too; but it's kind of waste to just remove the annotation while it can be beneficial here. Wonder what `lxml_html_clean` maintainer would think?

**Comment by frenzymadness** [comment]
Thank you for the report! I didn't know your project. I think that a stable codebase like we have here might benefit from having type annotations so I am open to including it and having mypy in CI as well.

**Comment by abelcheung** [comment]
Nice, I'll start creating a PR in coming dates. There could be things needing attention though:

1. It operates on `HtmlElement` (duh), and some of the funcs support `ElementTree`, so an external annotation dependency is unavoidable. I'll take care to make it usable for both `types-lxml` and `lxml-stub`.

2. I can see that `lxml_html_clean` is supporting Python 3.6. While fairly confident with 3.7 support, I'm not so sure if 3.6 support is achievable. Needs more investigation though, I'll post any update on this issue later on.

**Comment by frenzymadness** [comment]
I'd keep any typing-related dependencies optional so we can install them only in a new dedicated environment in tox that we're gonna use for type checking. If compatibility with Python 3.6 would mean any troubles, we can keep type annotations in separate files and run mypy in a tox environment with one of the newer Python.

**Comment by abelcheung** [comment]
Great, then there's no need to care about python version support in code. I'm sending PR for review.
